import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { QRScanner } from "@/components/QRScanner";
import { MapComponent } from "@/components/MapComponent";
import { Scan, MapPin, Shield, CheckCircle } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import ashwagandhaTrace from "@/assets/ashwagandha-trace.jpg";

export const ConsumerScanner = () => {
  const [scannedData, setScannedData] = useState<any>(null);
  const { toast } = useToast();

  const handleQRScan = async (result: string) => {
    try {
      // First try to parse as JSON (direct QR data)
      let qrData;
      try {
        qrData = JSON.parse(result);
      } catch {
        // If not JSON, treat as raw data
        qrData = { rawData: result };
      }

      // If we have structured QR data, fetch full details from backend
      if (qrData.transactionId || qrData.id) {
        console.log('Fetching product details for QR data:', qrData);
        
        const { data: productDetails, error } = await supabase.functions.invoke('get-product-details', {
          body: { qrData: result }
        });

        if (error) {
          console.error('Error fetching product details:', error);
          toast({
            title: "Error",
            description: "Failed to fetch product details",
            variant: "destructive",
          });
          setScannedData(qrData); // Fall back to original QR data
        } else {
          console.log('Successfully fetched product details:', productDetails);
          setScannedData(productDetails);
          toast({
            title: "Product Verified",
            description: "Successfully retrieved blockchain-verified product details",
          });
        }
      } else {
        // Use original QR data if no transaction ID
        setScannedData(qrData);
      }
    } catch (error) {
      console.error('Invalid QR code data:', error);
      setScannedData({ rawData: result });
    }
  };

  return (
    <section className="py-20 bg-gradient-to-br from-herb-sage/10 to-herb-gold/10">
      <div className="container mx-auto px-4">
        <div className="text-center max-w-3xl mx-auto mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 bg-gradient-to-r from-herb-green to-herb-sage bg-clip-text text-transparent">
            Consumer Transparency Portal
          </h2>
          <p className="text-lg text-muted-foreground">
            Scan QR codes generated by farmers on herb products to discover their complete journey from farm to shelf.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* QR Scanner Section */}
          <div className="space-y-6">
            <QRScanner onScan={handleQRScan} />
            
            {/* Demo functionality - hidden by default, can be activated with double-click */}
            <div 
              className="text-center opacity-30 hover:opacity-60 transition-opacity"
              onDoubleClick={() => handleQRScan(JSON.stringify({
                id: "demo-id-12345",
                transactionId: "txn_demo123456789",
                blockchainHash: "0x1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t",
                herbType: "ashwagandha",
                quantity: "5",
                quality: "premium",
                location: "28.6139,77.2090",
                locationAddress: "Organic Farm, Delhi Region, India",
                timestamp: "2024-01-15T10:30:00Z",
                collectionDate: "2024-01-15T10:30:00Z",
                verified: true,
                status: "recorded"
              }))}
            >
              <p className="text-xs text-muted-foreground cursor-pointer">
                Double-click for demo
              </p>
            </div>
          </div>

          {/* Results Display */}
          <div className="space-y-6">
            {scannedData ? (
              <>
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <Shield className="w-5 h-5 text-herb-green" />
                      Blockchain Verification
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <div className="flex items-center gap-2 text-green-600">
                      <CheckCircle className="w-4 h-4" />
                      <span className="font-medium">Verified on Blockchain</span>
                    </div>
                    {scannedData.transactionId && (
                      <p className="text-sm text-muted-foreground">
                        <strong>Transaction ID:</strong> {scannedData.transactionId}
                      </p>
                    )}
                    {scannedData.blockchainHash && (
                      <p className="text-sm text-muted-foreground">
                        <strong>Hash:</strong> {scannedData.blockchainHash}
                      </p>
                    )}
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle>Product Information</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <p className="text-sm font-medium text-muted-foreground">Herb Type</p>
                        <p className="capitalize">{scannedData.herbType || 'N/A'}</p>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-muted-foreground">Quantity</p>
                        <p>{scannedData.quantity ? `${scannedData.quantity}kg` : 'N/A'}</p>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-muted-foreground">Quality Grade</p>
                        <Badge variant="secondary" className="capitalize">
                          {scannedData.quality || 'N/A'}
                        </Badge>
                      </div>
                      <div>
                        <p className="text-sm font-medium text-muted-foreground">Collection Date</p>
                        <p>{scannedData.timestamp ? new Date(scannedData.timestamp).toLocaleDateString() : 'N/A'}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {(scannedData.location || scannedData.coordinates) && (
                  <Card>
                    <CardHeader>
                      <CardTitle className="flex items-center gap-2">
                        <MapPin className="w-5 h-5" />
                        Collection Location
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      {scannedData.locationAddress && (
                        <p className="text-sm text-muted-foreground mb-4">
                          <strong>Address:</strong> {scannedData.locationAddress}
                        </p>
                      )}
                      <MapComponent 
                        locations={[{
                          lat: scannedData.coordinates ? scannedData.coordinates.lat : parseFloat(scannedData.location.split(',')[0]),
                          lng: scannedData.coordinates ? scannedData.coordinates.lng : parseFloat(scannedData.location.split(',')[1]),
                          title: `${scannedData.herbType || 'Herb'} Collection Site`,
                          description: `Collected on ${scannedData.collectionDate ? new Date(scannedData.collectionDate).toLocaleDateString() : (scannedData.timestamp ? new Date(scannedData.timestamp).toLocaleDateString() : 'Unknown date')}`
                        }]}
                        height="250px"
                      />
                    </CardContent>
                  </Card>
                )}
              </>
            ) : (
              <Card>
                <CardHeader>
                  <CardTitle>Scan a QR Code to View Results</CardTitle>
                </CardHeader>
                <CardContent className="text-center py-12">
                  <Scan className="w-16 h-16 mx-auto mb-4 text-muted-foreground opacity-50" />
                  <p className="text-muted-foreground">
                    Use the scanner or try the demo data to see detailed traceability information.
                  </p>
                </CardContent>
              </Card>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};